package com.bullet.employee;

import com.bullet.person.Gender;
import com.bullet.person.MyDate;

public class Outline {

    /*
    Employee ID: 101,Firstname: Emily,Lastname: Chen,Gender: Female,Email: mailto:emily.chen@company.com,Phone Number:123-456-7890,Department: Marketing,Job Title: Marketing Manager,Salary: $80,000,Date Joined: 2018-01-01
Employee ID: 102,Firstname: David,Lastname: Lee,Gender: Male,Email: mailto:david.lee@company.com,Phone Number: 987-654-3210,Department: Sales,Job Title: Sales Representative,Salary: $60,000,Date Joined: 2020-06-01
Employee ID: 103,Firstname: Sophia,Lastname: Patel,Gender: Female,Email: mailto:sophia.patel@company.com,Phone Number: 555-123-4567,Department: IT,Job Title: Software Engineer,Salary: $90,000,Date Joined: 2019-03-01
Employee ID: 104,Firstname: Jackson,Lastname: Brown,Gender: Male,Email: mailto:jackson.brown@company.com,Phone Number: 111-222-3333,Department: Finance,Job Title: Financial Analyst,Salary: $70,000,Date Joined: 2017-09-01
Employee ID: 105,Firstname: Ava,Lastname: Taylor,Gender: Female,Email: mailto:ava.taylor@company.com,Phone Number: 444-555-6666,Department: HR,Job Title: HR Generalist,Salary: $50,000,Date Joined: 2020-01-01


    * */

    String firstname;
    String lastname;
    Gender gender;
    String email;
    String phonenumber;
    String department;
    String jobtitle;
    double salary;
    MyDate datejoined;


    /*
    MENU ITEMS

    #ADMIN
    #RUN PAYROLL
    #EMPLOYEE DETAILS
    #PAYROLL ARCHIVE
    #REPORTS
    #TAX TABLES
    #EMPLOYEE BENEFITS
    #BACK UP
    #LEAVE MANAGEMENT/ADMINISTRATION
    #OVERTIME
    #BENEFIT PLAN

    /******************  */
    /*
    #EMPLOYEE DATA
    #PAYMENT TYPE - monthly, weekly, fortnight, daily
    #SEARCH BOX
    #TABLE VIEW

            #EMPLOYEE NUMBER - autogenerated
            #NAME
            #OTHER NAMES
            #LAST NAME
            #MARITAL STATUS
            #GENDER
            #DATE OF BIRTH
            #NATIONAL ID

            CONTACT DETAILS
            #ADDRESS
            #CITY
            #COUNTRY
            #LANDLINE
            #CELL NUMBER
            #EMAIL

            PAYMENT DETAILS(EMPLOYMENT CONTRACT DETAILS)
            #EMPLOYEE NUMBER
            #POSITION
            #DEPARTMENT
            #BRANCH
            #BASIC EARNINGS
            #CURRENCY
                #DAILY RATE
                #HOURLY RATE
                #NUMBER OF DAYS WORKED
                #NUMBER OF HOURS WORKED


            PAYMENT STATUS(EMPLOYMENT CONTRACT STATUS)
            #CONTRACT TYPE
                #SHORT TERM
                #GRADUATE TRAINEE
                #PERMANENT
                #STUDENT
            #ACTIVE STATUS
            #GRADE
            #PAY SCHEDULE - daily to monthly
            #START DATE
            #TERMINATION DATE
            REASONS FOR TERMINATION



    #REPORTS
        #PAYSLIPS
        #LEAVE DAYS
        #OVERTIME
        #LOANS AND DEDUCTIONS


    */

    /*.......................*/
}
